# Generated by Django 2.0.2 on 2018-02-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180215_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_num',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='student_num',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
