# Generated by Django 2.0.2 on 2018-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180216_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='org_image',
            field=models.ImageField(blank=True, null=True, upload_to='org/%Y/%m', verbose_name='机构封面图'),
        ),
    ]
