# Generated by Django 2.0.2 on 2018-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180217_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='teacher/%Y/%m', verbose_name='教师照片'),
        ),
    ]
