# Generated by Django 2.0.2 on 2018-02-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='teacher/%Y/%m', verbose_name='教师照片'),
        ),
    ]
