# Generated by Django 2.0.2 on 2018-02-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180217_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_num',
        ),
    ]
