# Generated by Django 2.0.2 on 2018-02-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_courseorg_course_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
    ]
