# Generated by Django 2.0.2 on 2018-02-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180205_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='head_image',
            new_name='ei',
        ),
    ]
