# Generated by Django 2.0.2 on 2018-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180217_1724'),
        ('course', '0002_auto_20180213_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
