# Generated by Django 2.0.2 on 2018-02-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='message',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='课程公告'),
        ),
    ]
