# Generated by Django 2.0.2 on 2018-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='访问地址'),
        ),
    ]
