# Generated by Django 2.0.2 on 2018-02-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_courseorg_course_num'),
        ('course', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='organization.Teacher', verbose_name='讲师'),
        ),
    ]
