# Generated by Django 2.0.2 on 2018-02-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='can_learn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学到知识'),
        ),
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课程须知'),
        ),
    ]
