# Generated by Django 2.0.2 on 2018-02-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180218_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='全国知名', max_length=4, verbose_name='课程标签'),
        ),
    ]
