# Generated by Django 2.0.2 on 2018-02-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180208_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(max_length=50, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
