# Generated by Django 2.0.2 on 2018-02-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180214_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=36, verbose_name='验证码'),
        ),
    ]
