# Generated by Django 2.0.2 on 2018-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180219_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码'), ('update', '修改邮箱')], max_length=10, verbose_name='验证类型'),
        ),
    ]
