# Generated by Django 2.0.2 on 2018-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180220_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='has_used',
            field=models.BooleanField(default=False, verbose_name='是否已经使用'),
        ),
    ]
