# Generated by Django 2.0.2 on 2018-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_emailverifyrecord_has_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownBanner',
            fields=[
            ],
            options={
                'verbose_name': '上架轮播图',
                'verbose_name_plural': '上架轮播图',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.banner',),
        ),
        migrations.CreateModel(
            name='UPBanner',
            fields=[
            ],
            options={
                'verbose_name': '上架轮播图',
                'verbose_name_plural': '上架轮播图',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.banner',),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_up',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
